name: Deploy prebuilt files to GitHub Pages

on:
  push:
    branches:
      - gh-pages # Pokreće se kada se izvrši push na `gh-pages` granu

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Direktno koristi `out` folder za deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
